version: '3.8'
services:
  nestjsapi-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - nestjsapi
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - nestjsapi
networks:
  nestjsapi: